### ISSUE TITLE
table of node counts per country

### ISSUE THREAD

**Issue by fab1an2** [brianshea2/meshmap.net#3] opened 2024-05-25 08:56 UTC
Please make a table of how many nodes there are in a country.
e.g. Poland = 1000 nodes
Czech Republic = 800 nodes (for a specific day)

**Comment by brianshea2** [comment] 2024-05-31 14:39
Duplicate of #4

**Comment by brianshea2** [comment] 2024-06-03 17:49
I misunderstood. This is not a duplicate of #4. #4 mentions use of a table as a possible solution for selecting between nodes on the same point on the map. This request is to more generically show the node lists as per-region tables in addition to the map.

**Comment by brianshea2** [comment] 2024-06-03 17:56
This request would be better suited by its own project. MeshMap is a map, and while it could offer some secondary tables, those tables would ultimately be sourced from the same data, not saving any bandwidth, and only containing nodes which are reporting position. Such tables instead would be better served by complete node lists (including neighbors of nodes reporting position), separated into regions. That is simply out of scope for this project. The program which collects the node data for the map, `meshobserv`, is freely available in this repo if someone wanted to modify it and start such a project.

**Comment by brianshea2** [comment] 2024-06-03 18:14
This is similar to the second ask in issue #4, but a bit simpler. As MeshMap only collects data for position-reporting nodes, such a table would be incomplete. We could have a table of the number of nodes displayed on the map per country, but I'm not sure where that table would go in the UI and I question its usefulness. Open to comments and suggestions here.

Sorry for the confusion between this and #4 :)

**Closed** 2024-06-12 14:16 UTC
Labels: enhancement
