### ISSUE TITLE
Docker build issue

### ISSUE THREAD

**Issue by W0rmsy** [brianshea2/meshmap.net#17] opened 2024-07-20 16:05 UTC
Hello,

I'm trying to install meshmap for an offline project and I'm facing an error while trying to build the docker:

------
 > [build 6/7] RUN go mod tidy:
0.279 go: finding module for package github.com/eclipse/paho.mqtt.golang
0.279 go: finding module for package github.com/brianshea2/meshmap.net/internal/meshtastic/generated
0.279 go: finding module for package google.golang.org/protobuf/proto
0.607 go: downloading google.golang.org/protobuf v1.34.2
0.618 go: downloading github.com/eclipse/paho.mqtt.golang v1.4.3
1.388 go: found google.golang.org/protobuf/proto in google.golang.org/protobuf v1.34.2
1.388 go: found github.com/eclipse/paho.mqtt.golang in github.com/eclipse/paho.mqtt.golang v1.4.3
1.391 go: downloading github.com/gorilla/websocket v1.5.0
1.391 go: downloading golang.org/x/net v0.8.0
1.391 go: downloading golang.org/x/sync v0.1.0
1.392 go: downloading github.com/google/go-cmp v0.5.5
1.476 go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
1.664 go: finding module for package github.com/brianshea2/meshmap.net/internal/meshtastic/generated
1.666 go: github.com/brianshea2/meshmap.net imports
1.666   github.com/brianshea2/meshmap.net/internal/meshtastic/generated: no matching versions for query "latest"
------
Dockerfile:6
--------------------
   4 |     COPY cmd/meshobserv ./
   5 |     COPY internal ./internal/
   6 | >>> RUN go mod tidy
   7 |     RUN go build -v -o meshobserv
   8 |
--------------------
ERROR: failed to solve: process "/bin/sh -c go mod tidy" did not complete successfully: exit code: 1

Am I doing something wrong ?

Thanks,
Regards,

**Comment by brianshea2** [comment] 2024-07-20 16:19
Duplicate of #1

**Closed by brianshea2** 2024-07-20 16:19 UTC

**Comment by brianshea2** [comment] 2024-07-20 16:20
Please use the build script in the scripts dir. Let me know if you have any other issues.

**Comment by W0rmsy** [comment] 2024-07-20 16:50
Indeed my fault.
While using the script it builds correctly. However when I try to use the script to start it, it loop crash

2024/07/20 16:46:46 [info] loaded 0 nodes from disk
2024/07/20 16:46:46 [warn] mqtt: [store]    memorystore wiped
2024/07/20 16:46:46 [info] connected
2024/07/20 16:46:46 [warn] mqtt: [store]    memorystore del: message 1 not found
2024/07/20 16:46:46 [info] subscribed
2024/07/20 16:47:46 [error] write nodes: open /data/meshmap.net/website/nodes.json1939447248: no such file or directory

Second question, isn't expose missing from Dockerfile and -p 80:80 from the run command to access it ?

Thanks :)

**Comment by W0rmsy** [comment] 2024-07-20 16:56
Ok my bad again, understood that the website is not part of the docker and only the json file is modified from the docker. Now it works once the file creates

**Comment by brianshea2** [comment] 2024-07-20 16:57
meshobserv doesn't run a webserver itself, all it does is keep the nodes.json file updated. there's a sample config in the configs directory to use nginx. that's up to you :)

it's dying because it can't write that file. you'll likely need to set it up how you see fit on your system and modify the path to the json file.
